const label = {
  9: [
    {
      key: "gongchengmingcheng",
      title: "工程名称",
      // 是否隐藏
      visible: true,
      editTitle: true,
      switchVisible: false,
    },
    {
      key: "shigongquyu",
      title: "施工区域",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "shigongneirong",
      title: "施工内容",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "shigongzerenren",
      title: "施工责任人",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "jianlizerenren",
      title: "监理责任人",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "shijian",
      title: "拍摄时间",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "tianqi",
      title: "天气",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "didian",
      title: "地点",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "jingdu",
      title: "经度",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "weidu",
      title: "纬度",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "beizhu",
      title: "备注",
      visible: true,
      editTitle: true,
      switchVisible: true,
    },
    {
      key: "jianshedanwei",
      title: "建设单位",
      visible: true,
      editTitle: true,
      switchVisible: true,
      bg: true,
    },
    {
      key: "jianlidanwei",
      title: "监理单位",
      visible: true,
      editTitle: true,
      switchVisible: true,
      bg: true,
    },
    {
      key: "shigongdanwei",
      title: "施工单位",
      visible: true,
      editTitle: true,
      switchVisible: true,
      bg: true,
    },
  ],
};

export default label;
